In [84]:
import pandas as pd
fIn=pd.read_csv("wipdata.csv", encoding= "latin1")
keep_col = ["adm0_name", "adm1_name", "mkt_name", "cm_name", "cur_name", "pt_name", "um_id", "um_name", "mp_month", "mp_year", "mp_price"]
keep_row = ["Afghanistan", "Iraq", "Iran", "Lebanon", "Palestine", "Pakistan"]
new_f= fIn[keep_col]
new_f.to_csv("nette_prizes_pd_midoosten.csv", encoding="utf-8", index=True)

In [98]:
new_f
data = new_f.loc[new_f['adm0_name'] == 'Afghanistan']

                   adm0_name      adm1_name      mkt_name  cm_name cur_name  \
636073  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636074  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636075  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636076  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636077  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636078  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636079  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636080  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636081  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636082  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636083  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636084  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636085  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636086  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636087  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636088  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636089  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636090  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636091  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636092  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636093  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636094  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636095  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636096  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636097  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636098  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636099  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636100  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636101  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
636102  Syrian Arab Republic  City-Damascus  Sheikh Sa'ad     Rice      SYP
...                      ...            ...           ...      ...      ...
660115  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660116  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660117  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660118  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660119  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660120  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660121  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660122  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660123  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660124  Syrian Arab Republic         Aleppo        Afreen   Yogurt      SYP
660125  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660126  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660127  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660128  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660129  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660130  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660131  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660132  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660133  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660134  Syrian Arab Republic         Aleppo        Afreen   Cheese      SYP
660135  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP
660136  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP
660137  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP
660138  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP
660139  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP
660140  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP
660141  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP
660142  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP
660143  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP
660144  Syrian Arab Republic         Aleppo        Afreen  Parsley      SYP

       pt_name  um_id um_name  mp_month  mp_year   mp_price
636073  Retail      5      KG         7     2012    55.0000
636074  Retail      5      KG         8     2012    80.0000
636075  Retail      5      KG         9     2012    80.0000
636076  Retail      5      KG         5     2013    95.0000
636077  Retail      5      KG         6     2013   106.2500
636078  Retail      5      KG         7     2013   188.0000
636079  Retail      5      KG         8     2013   295.0000
636080  Retail      5      KG         9     2013   275.0000
636081  Retail      5      KG        10     2013   295.0000
636082  Retail      5      KG        11     2013   295.0000
636083  Retail      5      KG        12     2013   295.0000
636084  Retail      5      KG         1     2014   147.0000
636085  Retail      5      KG         2     2014   181.2500
636086  Retail      5      KG         3     2014   196.6667
636087  Retail      5      KG         4     2014   208.3333
636088  Retail      5      KG         5     2014   190.0000
636089  Retail      5      KG         6     2014   193.7500
636090  Retail      5      KG         7     2014   193.7500
636091  Retail      5      KG         8     2014   217.5000
636092  Retail      5      KG         9     2014   217.5000
636093  Retail      5      KG        10     2014   211.2500
636094  Retail      5      KG        11     2014   235.0000
636095  Retail      5      KG        12     2014   218.0000
636096  Retail      5      KG         1     2015   238.0000
636097  Retail      5      KG         2     2015   228.0000
636098  Retail      5      KG         3     2015   258.0000
636099  Retail      5      KG         4     2015   272.5000
636100  Retail      5      KG         5     2015   197.0000
636101  Retail      5      KG         6     2015   215.0000
636102  Retail      5      KG         7     2015   215.0000
...        ...    ...     ...       ...      ...        ...
660115  Retail      5      KG        12     2016   450.0000
660116  Retail      5      KG         1     2017   400.0000
660117  Retail      5      KG         2     2017   380.0000
660118  Retail      5      KG         3     2017   370.0000
660119  Retail      5      KG         4     2017   355.0000
660120  Retail      5      KG         5     2017   325.0000
660121  Retail      5      KG         6     2017   325.0000
660122  Retail      5      KG         7     2017   325.0000
660123  Retail      5      KG         8     2017   325.0000
660124  Retail      5      KG         9     2017   368.0000
660125  Retail      5      KG        12     2016  2200.0000
660126  Retail      5      KG         1     2017  1563.0000
660127  Retail      5      KG         2     2017  1575.0000
660128  Retail      5      KG         3     2017  1525.0000
660129  Retail      5      KG         4     2017  1425.0000
660130  Retail      5      KG         5     2017  1350.0000
660131  Retail      5      KG         6     2017  1450.0000
660132  Retail      5      KG         7     2017  1500.0000
660133  Retail      5      KG         8     2017  1650.0000
660134  Retail      5      KG         9     2017  1800.0000
660135  Retail     75  Packet        12     2016   140.0000
660136  Retail     75  Packet         1     2017   108.0000
660137  Retail     75  Packet         2     2017    88.0000
660138  Retail     75  Packet         3     2017    70.0000
660139  Retail     75  Packet         4     2017    45.0000
660140  Retail     75  Packet         5     2017    25.0000
660141  Retail     75  Packet         6     2017    20.0000
660142  Retail     75  Packet         7     2017    20.0000
660143  Retail     75  Packet         8     2017    25.0000
660144  Retail     75  Packet         9     2017    30.0000

[24072 rows x 11 columns]

In [109]:
me1 = new_f.loc[new_f['adm0_name'] == 'Syrian Arab Republic']
me2 = new_f.loc[new_f['adm0_name'] == 'Afghanistan']
me3 = new_f.loc[new_f['adm0_name'] == 'Iraq']
me4 = new_f.loc[new_f['adm0_name'] == 'Lebanon']
me5 = new_f.loc[new_f['adm0_name'] == 'Palestine']
me6 = new_f.loc[new_f['adm0_name'] == 'Pakistan']

predata_middle_east = [me1, me2, me3, me4, me5, me6]
data_middle_east = pd.concat(predata_middle_east)
data_middle_east

,adm0_name,adm1_name,mkt_name,cm_name,cur_name,pt_name,um_id,um_name,mp_month,mp_year,mp_price
636073,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,7,2012,55.0000
636074,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,8,2012,80.0000
636075,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,9,2012,80.0000
636076,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,5,2013,95.0000
636077,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,6,2013,106.2500
636078,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,7,2013,188.0000
636079,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,8,2013,295.0000
636080,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,9,2013,275.0000
636081,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,10,2013,295.0000
636082,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,11,2013,295.0000
636083,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,12,2013,295.0000
636084,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,1,2014,147.0000
636085,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,2,2014,181.2500
636086,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,3,2014,196.6667
636087,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,4,2014,208.3333
636088,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,5,2014,190.0000
636089,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,6,2014,193.7500
636090,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,7,2014,193.7500
636091,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,8,2014,217.5000
636092,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,9,2014,217.5000
636093,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,10,2014,211.2500
636094,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,11,2014,235.0000
636095,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,12,2014,218.0000
636096,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,1,2015,238.0000
636097,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,2,2015,228.0000
636098,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,3,2015,258.0000
636099,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,4,2015,272.5000
636100,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,5,2015,197.0000
636101,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,6,2015,215.0000
636102,Syrian Arab Republic,City-Damascus,Sheikh Sa'ad,Rice,SYP,Retail,5,KG,7,2015,215.0000
...,...,...,...,...,...,...,...,...,...,...,...
471155,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,4,2015,550.0000
471156,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,5,2015,550.0000
471157,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,6,2015,550.0000
471158,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,7,2015,550.0000
471159,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,8,2015,550.0000
471160,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,9,2015,550.0000
471161,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,10,2015,550.0000
471162,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,11,2015,550.0000
471163,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,12,2015,550.0000
471164,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,1,2016,550.0000
471165,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,2,2016,550.0000
471166,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,3,2016,550.0000
471167,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,4,2016,550.0000
471168,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,5,2016,550.0000
471169,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,6,2016,550.0000
471170,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,7,2016,550.0000
471171,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,8,2016,550.0000
471172,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,9,2016,550.0000
471173,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,10,2016,550.0000
471174,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,11,2016,550.0000
471175,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,12,2016,550.0000
471176,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,1,2017,550.0000
471177,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,2,2017,550.0000
471178,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,3,2017,550.0000
471179,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,4,2017,550.0000
471180,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,5,2017,550.0000
471181,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,6,2017,550.0000
471182,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,7,2017,550.0000
471183,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,8,2017,550.0000
471184,Pakistan,Balochistan,Quetta,"Wage (non-qualified labour, non-agricultural)",PKR,Retail,51,Day,9,2017,550.0000